#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

// Error function used for reporting issues
void error(const char *msg) {
  perror(msg);
  exit(1);
} 

// Set up the address struct for the server socket
void setupAddressStruct(struct sockaddr_in* address, 
                        int portNumber){
 
  // Clear out the address struct
  memset((char*) address, '\0', sizeof(*address)); 

  // The address should be network capable
  address->sin_family = AF_INET;
  // Store the port number
  address->sin_port = htons(portNumber);
  // Allow a client at any address to connect to this server
  address->sin_addr.s_addr = INADDR_ANY;
}

int main(int argc, char *argv[]){
  int connectionSocket, charsRead;
  char buffer[256];
  struct sockaddr_in serverAddress, clientAddress;
  socklen_t sizeOfClientInfo = sizeof(clientAddress);

  // Check usage & args
  if (argc < 2) { 
    fprintf(stderr,"USAGE: %s port\n", argv[0]); 
    exit(1);
  } 
  
  // Create the socket that will listen for connections
  int listenSocket = socket(AF_INET, SOCK_STREAM, 0);
  if (listenSocket < 0) {
    error("ERROR opening socket");
  }

  // Set up the address struct for the server socket
  setupAddressStruct(&serverAddress, atoi(argv[1]));

  // Associate the socket to the port
  if (bind(listenSocket, 
          (struct sockaddr *)&serverAddress, 
          sizeof(serverAddress)) < 0){
    error("ERROR on binding");
  }

  // Start listening for connetions. Allow up to 5 connections to queue up
  listen(listenSocket, 5); 
  
  // Accept a connection, blocking if one is not available until one connects
  while(1){
    // Accept the connection request which creates a connection socket
    connectionSocket = accept(listenSocket, 
                (struct sockaddr *)&clientAddress, 
                &sizeOfClientInfo); 
    if (connectionSocket < 0){
      error("ERROR on accept");
    }

    printf("SERVER: Connected to client running at host %d port %d\n", 
                          ntohs(clientAddress.sin_addr.s_addr),
                          ntohs(clientAddress.sin_port));

    // Get the message from the client and display it
    memset(buffer, '\0', 256);
    // Read the client's message from the socket
    charsRead = recv(connectionSocket, buffer, 255, 0);

    for (int i=0; i<strlen(buffer); i++){
      if (buffer[i] == '1'){
        error("ERROR. enc_client cannot connect to dec_server");
      }
    }

    char *inputString;
    char *key;

    //I catted the key and message together to make them easier to send from client to server. This is separating them
    inputString = strtok(buffer, "2");
    key = strtok(NULL, "2"); //NULL tells strtok to continue from pervious string

    char *decodedOut = malloc((strlen(inputString)+2) * sizeof(char));

    int i=0;
    while ((inputString[i]) != '\0'){ //Less volatile than a for loop set so strlen inputString

          if (inputString[i] == '\n'){
          break;
        }

        //Prepping vars for math by converting char values into strings
        int keyGenPos = key[i];
        if (keyGenPos == 32){ //Converting spaces to a num between 1 and 27
            keyGenPos = 27;
        }
        else{
            keyGenPos -= 64; //Converting letters to a num between 1 and 27
        }
        int inputPos = inputString[i];
        if (inputPos == 32){ //Converting spaces to a num between 1 and 27
            inputPos = 27;
        }
        else{
            inputPos -= 64; //Converting letters to a num between 1 and 27
        }

        //If the input isn't one of the allowed chars then the program rejects the code
        if (inputPos < 1 || inputPos > 27){ //since key was generated by keygen, I'm only checking input
            fprintf(stderr, "ERROR: invalid char, %c found in input string\n", key[i]);
            return 1;
        }

        //adding position of keygen to input. Giving properly randomized num
        inputPos -= keyGenPos;

        //Preventing overflow by ensuring numbers are never outside of range given
        while (inputPos < 1){
            inputPos += 27;
        }

        //Final step. Convert finished numbers into encoded text and output
        if (inputPos == 27){
            decodedOut[i] = 32;
        }
        else{
            decodedOut[i] = inputPos + 64;
        }

        i++;
    }
    decodedOut[i] = '\n';
    decodedOut[i+1] = '\0'; //add null terminator to encoded string
    
    //keyRead = recv(connectionSocket, buffer2, 255, 0); 
    if (charsRead < 0){
      error("ERROR reading from socket");
    }
    printf("SERVER: I received this from the client: \"%s\"\n", buffer);
    //printf("%s\n", buffer2);

    // Send the encoded text back to client
    charsRead = send(connectionSocket, decodedOut, strlen(decodedOut), 0);

    if (charsRead < 0){
      error("ERROR writing to socket");
    }
    // Close the connection socket for this client
    close(connectionSocket); 
  }
  // Close the listening socket
  close(listenSocket); 
  return 0;
}
